# ScheduledAnnouncements Configuration

# Global settings
settings:
  prefix:
    text: "[Announcement]"  # Set to "" (empty string) to disable the global prefix
    color: "gold"  # Color names: https://jd.advntr.dev/api/4.17.0/net/kyori/adventure/text/format/NamedTextColor.html
  message_color: "yellow"  # Default color for all announcement messages

# Announcements Configuration
# Structure:
# announcements:
#   unique_identifier:
#     cron: "cron expression"
#     message: "Your message | Optional URL"
#     prefix:  # Optional: Overrides global prefix for this announcement
#       text: "Custom prefix"
#       color: "color_name"
#     message_color: "color_name"  # Optional: Overrides global message color

# Cron Expression Format: "Second Minute Hour DayOfMonth Month DayOfWeek Year"
# Use https://www.freeformatter.com/cron-expression-generator-quartz.html for help with cron expressions
# Time is based on the server's timezone

# Tips:
# - To add a clickable URL, append it to the message after a pipe character (|)
# - Use '/scheduledannouncements reload' after changing this config

announcements:
  server_advertise:
    cron: "0 0/30 * * * ?"  # Every 30 minutes
    message: "MinecraftOffline.net is a cool server!"
    prefix:
      text: "[Ad]"
      color: "green"
    message_color: "aqua"

  discord_invite:
    cron: "0 0 */3 * * ?"  # Every 3 hours
    message: "Join our Discord community - click here! | https://discord.gg/a83FESY3jF"
    prefix:
      text: ""  # Empty string disables the prefix for this announcement
    message_color: "light_purple"

  # Add more announcements as needed - the 'unique identifier' like 'server_advertise' and
  # 'discord_invite' seen above can be named anything at all.