name: ScheduledAnnouncements
version: '1.0.2'
main: com.jellypudding.scheduledAnnouncements.ScheduledAnnouncements
api-version: '1.21'
description: "Broadcasts scheduled announcements to all players."
author: AlphaAlex115
commands:
  scheduledannouncements:
    description: "Manage the ScheduledAnnouncements plugin"
    usage: "/scheduledannouncements reload"
    aliases: [sa]
    permission: scheduledannouncements.use
    permission-message: "You don't have permission to use the ScheduledAnnouncements commands."
permissions:
  scheduledannouncements.use:
    description: Allows use of the ScheduledAnnouncements command
    default: op
  scheduledannouncements.reload:
    description: Allows reloading the ScheduledAnnouncements plugin
    default: op